### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by passionetartufo** [Sathish-Vasudev/Article-Scraper#1]
Hello. Instead of saving the articles into docx is it possible to save the article in Excel? Possibly title under A column and content under B column?

**Comment by Sathish-Vasudev** [comment]
Yes, you can do that.
You can use **"xlsxwriter"** python library 
But I am afraid, the column with the content of the article might contain too much data.
It is possible but it will be pointless to load large content in a single cell.
Besides , content management is easier in a Word document than in a Spreadsheet.

You can check my other work , it's called DOI-Scraper.

[DOI-Scraper](https://github.com/Sathish-Vasudev/DOI-Scraper)

Here I create a log file that stores information of the retrieved data in an Excel file.

Fork both the projects and maybe combine both the codes at perfect points, you'll get what you're expecting.

**Comment by Sathish-Vasudev** [comment]
Yes it is possible, follow up with previous comment.
